choco install clink -y
choco install atom -y
choco install autohotkey -y
choco install autohotkey.install -y
choco install autohotkey_l -y
choco install axcrypt -y
choco install wincdemu -y
choco install bitwarden -y
choco install Brackets -y
choco install ccleaner -y
choco install chocolatey-core.extension -y
choco install chocolatey-windowsupdate.extension -y
choco install ConEmu -y
choco install curl -y
choco install cyberduck -y
choco install Cygwin -y
choco install filezilla -y
choco install filezilla.server -y
choco install git -y
choco install git.install -y
choco install gitkraken -y
choco install hugo -y
choco install hyper -y
choco install InnoSetup -y
choco install intellijidea-community -y
choco install javaruntime -y
choco install jdk8 -y
choco install jre8 -y
choco install kdevelop -y
choco install manictime.install -y
choco install MarkdownMonster -y
choco install msys2 -y
choco install mysql -y
choco install vnodejs.install -y
choco install paint.net -y
choco install putty.install -y
choco install python2 -y
choco install python3 -y
choco install rescuetime -y
choco install qbittorrent -y
choco install ruby -y
choco install ruby2.devkit -y
choco install rufus -y
choco install rufus.install -y
choco install rust -y
choco install speccy -y
choco install sublimetext3 -y
choco install vagrant -y
choco install virtualbox -y
choco install visualstudiocode -y
choco install webpi -y